version: "3.8"

services:
  backend:
    build:
      context: ../.. # Build from workspace root
      dockerfile: apps/backend/Dockerfile
    container_name: iagent-backend
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
      # Add your environment variables here
      # - MONGODB_URI=${MONGODB_URI}
      # - JWT_SECRET=${JWT_SECRET}
    volumes:
      # Optional: Mount for development logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "const http=require('http');const options={host:'localhost',port:3000,path:'/api',timeout:2000};const req=http.request(options,(res)=>{process.exit(res.statusCode<400?0:1)});req.on('error',()=>process.exit(1));req.end();",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - iagent-network

  # Optional: Add MongoDB if needed
  # mongodb:
  #   image: mongo:7-jammy
  #   container_name: iagent-mongodb
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - iagent-network

networks:
  iagent-network:
    driver: bridge

volumes:
  # mongodb_data:
  logs:
